
server:
  port: 8001
              
spring:
  boot:
    admin:
      client:
        url: http://localhost:8000
        username: admin
        password: 111111
  application:
    name: "Admin Client2"
    
management:
  security: 
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

foo: xxx